In [21]:
import numpy as np
t1 = np.array([[1,1,2,2,3],[1,2,2,2,2]])
d1 = np.array([0.1,0.2333,0.5,0.2,1.0],[1,2,3,4,5])


In [24]:
import numpy as np

# Given arrays
t1 = np.array([[0, 0, 1, 1, 2], [0, 1, 1, 1, 1]])
d1 = np.array([[0.1, 0.2, 0.5, 0.2, 1.0], [1, 2, 3, 4, 5]])

# Initialize the output array with zeros
output = [np.zeros(t1.max()+1), np.zeros(t1.max()+1)]

# Sum the values in d1 using the indices from t1
for i in range(t1.shape[0]):
    np.add.at(output[i], t1[i], d1[i])

# Convert output to the desired format
output = [output[0].tolist(), [int(x) for x in output[1]]]

print(output)


[[0.30000000000000004, 0.7, 1.0], [1, 14, 0]]


In [20]:
u, c, ind , inv = np.unique(t1,return_counts=1,return_index=1,return_inverse=1)
print(u)
print(c)
print(ind)
print(inv)
#print(np.add.at(t1))

[1 2 3 4]
[0 2 4 9]
[0 0 1 1 2 0 1 2 1 3]
[3 4 2 1]
